### PR TITLE
Copy tree fix

### LINKED ISSUE #122: copy-tree fail when some non-leaf directories in the tree are not writable
Given something like:
```sh
mkdir -p src/a/b
chmod -R 555 src
```
trying to do
```clojure
(fs/copy-tree "src" "dst")
```
fails with
```
Type:     java.nio.file.AccessDeniedException
Message:  /dst/a/b
```
and afaics explicitlty passing `:posix-file-permissions` also doesn't help.

Regular. `cp -r src dest` works. I assume it creates the destination tree writable and only afterwards sets the permissions like found on the source.

### PR DESCRIPTION
**Pull request by Sohalt**
Fixes #122.

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/babashka/babashka/blob/master/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/babashka/fs/blob/master/CHANGELOG.md) file with a description of the addressed issue.

This should ideally also restore the permissions on the directory in post-visit-dir on Windows.

### CODE REVIEW

File: test/babashka/fs_test.clj [hunk 1]
```diff
@@ -218,6 +218,15 @@
     (is (fs/exists? (fs/file tmp"foo2" "foo" "1"))
         "The nested destination directory is not created when it doesn't exist")))
 
+(deftest copy-tree-nested-ro-dir-test
+  (fs/with-temp-dir [tmp {}]
+    ;; https://github.com/babashka/fs/issues/122
+    (fs/create-dirs (fs/path tmp "src" "foo" "bar"))
+    (fs/set-posix-file-permissions (fs/path tmp "src" "foo") "r-xr-xr-x")
```
Comment (borkdude) [inline test/babashka/fs_test.clj:225]: This fails on Windows

Comment (Sohalt) [reply test/babashka/fs_test.clj]: Looks like directories on Windows are always writable, according to [this]( https://answers.microsoft.com/en-us/windows/forum/all/all-folders-are-now-read-only-windows-10/0ca1880f-e997-46af-bd85-042a53fc078e) post.
I don't have a Windows system to check. I adjusted the test to skip this check on Windows.

Comment (borkdude) [reply test/babashka/fs_test.clj]: > I adjusted the test to skip this check on Windows.

Seems fine to me.

File: src/babashka/fs.cljc [hunk 2]
```diff
@@ -424,6 +424,9 @@
   ([path {:keys [:posix-file-permissions]}]
    (Files/createDirectories (as-path path) (posix->attrs posix-file-permissions))))
 
+(declare posix-file-permissions)
+(declare u+wx)
```
Comment (borkdude) [inline src/babashka/fs.cljc:428]: Let's just move these functions higher up so they appear here.

File: src/babashka/fs.cljc [hunk 3]
```diff
@@ -462,7 +466,16 @@
                                                        ^"[Ljava.nio.file.CopyOption;"
                                                        copy-options)
                                            :continue)
-                                         :continue)}))))
+                                         :continue)
+                           :post-visit-dir (fn [dir _ex]
+                                             (let [rel (relativize from dir)
+                                                   to-dir (path to rel)]
+                                               (if win?
```
Comment (borkdude) [inline src/babashka/fs.cljc:473]: Since this problem doesn't exist on Windows, we can simply do nothing then, right?

File: src/babashka/fs.cljc [hunk 4]
```diff
@@ -453,7 +456,8 @@
                                               (when-not (Files/exists to-dir link-options)
                                                 (Files/copy ^Path dir to-dir
                                                             ^"[Ljava.nio.file.CopyOption;"
-                                                            copy-options)))
+                                                            copy-options)
+                                                (u+wx to-dir)))
```
Comment (borkdude) [inline src/babashka/fs.cljc:460]: Similar here, let's do nothing on Windows

**Comment by borkdude** [comment]
Thanks!
