### PR TITLE
`which` updates: `:paths` and absolute `program`

### LINKED ISSUE #94: Consider allowing non-relative paths for fs/which
## Background
On Windows `babashka.fs/which` will automatically find `foo.exe` (and other `:win-exts`) for `foo`.

This is very helpful. We often don't really care about the Windows executable extension.

## Problem
`which` currently throws on non-relative paths.

For example, let's say I want to find the executable for `java` on Windows.
Instead of finding the `java` executable on the `PATH`, I want to use `JAVA_HOME`.

From a Windows 10 in PowerShell:

```Clojure
PS C:\Users\lee> clj --version
Clojure CLI version (deps.clj) 1.11.1.1252
PS C:\Users\lee> clj -Sdeps "{:deps {babashka/fs {:mvn/version \`"0.3.17\`"}}}"
Clojure 1.11.1
user=> (require '[babashka.fs :as fs])
nil
```
Finding java on the path works great:
```Clojure
user=> (fs/which "java")
#object[sun.nio.fs.WindowsPath 0x3e3861d7 "C:\\Users\\lee\\scoop\\apps\\graalvm22-jdk17\\current\\bin\\java.exe"]
```

But maybe we want to find it via `JAVA_HOME`.
First, let's show that `java.exe` exists through `JAVA_HOME`:
```Clojure
user=> (fs/exists? (fs/file (System/getenv "JAVA_HOME") "bin" "java.exe"))
true
```

Ok, now let's try to find `java.exe` through `JAVA_HOME` using `which`:
```Clojure
user=> (fs/which (fs/file (System/getenv "JAVA_HOME") "bin" "java"))
Execution error (IllegalArgumentException) at babashka.fs/path (fs.cljc:57).
C:\Users\lee\scoop\apps\graalvm22-jdk17\current\bin\java.com is not a relative path
```
This does not work because `which` does not currently work on non-relative paths.

But if I contrive a relative path I can get `which` to find the exe:
```
user=> (System/getProperty "user.dir")
"C:\\Users\\lee"
user=> (fs/which (fs/file (fs/relativize (System/getProperty "user.dir") (System/getenv "JAVA_HOME")) "bin" "java"))
#object[sun.nio.fs.WindowsPath 0x61af1510 "scoop\\apps\\graalvm22-jdk17\\current\\bin\\java.exe"]
```

## Proposal
On Windows, `which` could resolve the executable extension even for non-relative paths.

## Additional Idea 
Perhaps `which` should allow non-relative paths in general?
If the passed in `program` already resolves to an executable, `which` could return it.

Given a `foobar.bat` in the current directory, we see this behaviour when looking up programs that specify a relative path:
```Clojure
user=> (fs/which "./foobar")
#object[sun.nio.fs.WindowsPath 0x11b455e5 ".\\foobar.bat"]
user=> (fs/which "./foobar.bat")
#object[sun.nio.fs.WindowsPath 0x6d025d1d ".\\foobar.bat"]
```
(Tangent: I wonder though, should we be returning the absolute or canonical path here?)

Operating on absolute paths seems to match the `which` zsh/bash behaviour on macOS/Linux:
```Shell
$ which java
/home/lee/.sdkman/candidates/java/current/bin/java
❯ which /home/lee/.sdkman/candidates/java/current/bin/java
/home/lee/.sdkman/candidates/java/current/bin/java
```
And the `get-command` behaviour on Windows PowerShell
```
PS C:\Users\lee> get-command java

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     java.exe                                           17.0.7.0   C:\Users\lee\scoop\apps\graalvm22-jdk1...


PS C:\Users\lee> get-command C:\\Users\\lee\\scoop\\apps\\graalvm22-jdk17\\current\\bin\\java.exe

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     java.exe                                           17.0.7.0   C:\Users\lee\scoop\apps\graalvm22-jdk17\current\bin\java.exe
```
And I guess kinda sorta the `where` behaviour Windows CMD shell:
```Batchfile
C:\Users\lee>where java
C:\Users\lee\scoop\apps\graalvm22-jdk17\current\bin\java.exe
C:\Users\lee\scoop\apps\temurin19-jdk\current\bin\java.exe
C:\Users\lee\scoop\apps\temurin8-jdk\current\bin\java.exe
C:\Users\lee\scoop\apps\temurin11-jdk\current\bin\java.exe

C:\Users\lee>where "C:\Users\lee\scoop\apps\graalvm22-jdk17\current\bin:java.exe"
C:\Users\lee\scoop\apps\graalvm22-jdk17\current\bin\java.exe
```

## Next Steps
Lemme know if I've missed some alternatives/nuances,etc that you see.

If this idea makes sense to you, happy to help out with a PR.

### PR DESCRIPTION
**Pull request by lread**
New `:paths` `opt` can be used to specify custom search paths. Default remains `(exec-paths)`

The `program` argument can now specify an absolute path.

Docstring updated and includes description of existing relative path support for `program` argument.

Relative and absolute path support for `program` make cross-platform support more convenient. For example `(fs/which ./myapp)` will find `./myapp` on macos/linux and `./myapp.exe` on Windows.

Closes #94

Please answer the following questions and leave the below in as part of your PR.

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/babashka/babashka/blob/master/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/babashka/fs/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

File: test/babashka/fs_test.clj [hunk 1]
```diff
@@ -287,34 +287,81 @@
...
     (when windows?
-      (testing "can find foo.cmd.bat"
-        (spit "on-path/foo.cmd.bat" "echo hello")
+      (testing "on windows, can find foo.cmd.bat"
         (let [expected (fs/path "on-path/foo.cmd.bat")]
           (is (= expected (fs/which "foo.cmd") (fs/which "foo.cmd.bat"))))))
     (when windows?
-      (testing "can overide win extension search"
-        (spit "on-path/foo.foo.ps1" "echo hello")
+      (testing "on windows, can overide win extension search"
```
Comment (borkdude) [inline test/babashka/fs_test.clj:307]: small typo

**Comment by borkdude** [comment]
Thanks a lot. This is now published as 0.4.18

**Comment by lread** [comment]
Awesome! Thanks!
